//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string book_name { get; set; }
        public int book_author { get; set; }
        public string book_isbn { get; set; }
        public int book_category { get; set; }
        public int book_language { get; set; }
        public int book_price { get; set; }
        public int book_amount { get; set; }
        public string book_info { get; set; }
        public Nullable<System.DateTime> book_publisher_date { get; set; }
        public System.DateTime book_add_date { get; set; }
        public int book_publisher { get; set; }
        public int book_type { get; set; }
        public string book_photo { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
